# Generated by Django 3.1.1 on 2020-11-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acetoon_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='reason',
            field=models.TextField(default='Help Nation'),
        ),
    ]
