# Generated by Django 3.1.3 on 2020-11-18 08:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acetoon_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='eligibility',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='prizes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
