# Generated by Django 3.1.3 on 2020-11-18 08:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acetoon_backend', '0002_auto_20201118_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
